services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ..:/var/www/html:rw
      - nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - db
      - php
    networks:
      - blackjack-network
  php:
    build:
      context: .
      dockerfile: dockerfile
    container_name: php
    restart: always
    volumes:
      - ..:/var/www/html
    command: > 
      bash -c "chown -R www-data:www-data /var/www/html 
      && php-fpm"
    networks:
      - blackjack-network
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=$DATABASENAME
      - MYSQL_USER=$DATABASEUSER
      - MYSQL_PASSWORD=$DATABASEPASS
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - blackjack_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - blackjack-network
networks:
  blackjack-network:
    driver: bridge
volumes:
  blackjack_data:
