FROM php:8.3-fpm 
# Install system dependencies
RUN apt-get update && apt-get install -y \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libpq-dev \
    libxml2-dev \
    libonig-dev \
    unzip \
    git \
    curl
RUN docker-php-ext-install pdo pdo_mysql mysqli zip xml
