<?php
/**
 * Installation script for Blackjack PHP application
 * This script allows users to set up database settings, create database tables,
 * and create a configuration file for the application.
 */

// Start session if not already started
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Define variables
$error = '';
$success = '';
$configFilePath = __DIR__ . '/config.php';

// Check if config file already exists (installation completed)
if (file_exists($configFilePath)) {
    header('Location: ../index.php');
    exit;
}

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Validate required fields
    $requiredFields = ['db_host', 'db_name', 'db_user', 'db_pass'];
    $missingFields = [];
    
    foreach ($requiredFields as $field) {
        if (empty($_POST[$field])) {
            $missingFields[] = $field;
        }
    }
    
    if (!empty($missingFields)) {
        $error = 'The following fields are required: ' . implode(', ', $missingFields);
    } else {
        // Get form data
        $db_host = $_POST['db_host'];
        $db_name = $_POST['db_name'];
        $db_user = $_POST['db_user'];
        $db_pass = $_POST['db_pass'];
        
        // Test database connection
        try {
            $conn = new PDO("mysql:host=$db_host", $db_user, $db_pass);
            $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            
            // Create database if it doesn't exist
            $conn->exec("CREATE DATABASE IF NOT EXISTS `$db_name`");
            $conn->exec("USE `$db_name`");
            
            // Read and execute SQL script
            $sqlFile = __DIR__ . '/../database/database.sql';
            $sql = file_get_contents($sqlFile);
            
            if ($sql) {
                // Execute each query separately
                $conn->exec($sql);
                
                // Create config.php
                $config_content = "<?php
/**
 * Database configuration file
 * Generated by install.php on " . date('Y-m-d H:i:s') . "
 */

// Database connection settings
define('DB_HOST', '" . addslashes($db_host) . "');
define('DB_NAME', '" . addslashes($db_name) . "');
define('DB_USER', '" . addslashes($db_user) . "');
define('DB_PASS', '" . addslashes($db_pass) . "');

// Create database connection
function getDbConnection() {
    try {
        \$conn = new PDO('mysql:host=' . DB_HOST . ';dbname=' . DB_NAME, DB_USER, DB_PASS);
        \$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        \$conn->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
        return \$conn;
    } catch (PDOException \$e) {
        // For production, you might want to log this instead
        die('Database Connection Error: ' . \$e->getMessage());
    }
}
";
                
                // Write config file
                if (file_put_contents($configFilePath, $config_content)) {
                    $success = 'Installation completed successfully!';
                    
                    // Update the database.php file to include config.php
                    $db_php_content = "<?php
/**
 * Database connection helper
 */
require_once __DIR__ . '/config.php';

// Get database connection instance
function getDb() {
    return getDbConnection();
}
";
                    file_put_contents(__DIR__ . '/database.php', $db_php_content);
                    
                } else {
                    $error = 'Failed to create configuration file. Please check file permissions.';
                }
            } else {
                $error = 'Failed to read SQL file.';
            }
        } catch (PDOException $e) {
            $error = 'Database Error: ' . $e->getMessage();
        }
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Install Blackjack PHP</title>
    <link rel="stylesheet" href="../assets/css/style.css">
    <style>
        body {
            background-color: #2c3e50;
            color: #ecf0f1;
            font-family: 'Arial', sans-serif;
        }
        .install-container {
            max-width: 600px;
            margin: 50px auto;
            background-color: #34495e;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }
        h1 {
            color: #1abc9c;
            text-align: center;
        }
        .form-group {
            margin-bottom: 15px;
        }
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }
        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            border-radius: 4px;
            border: 1px solid #7f8c8d;
            background-color: #ecf0f1;
            color: #2c3e50;
        }
        button {
            background-color: #1abc9c;
            color: white;
            border: none;
            padding: 10px 15px;
            cursor: pointer;
            font-size: 16px;
            font-weight: bold;
            border-radius: 4px;
            transition: background-color 0.3s;
        }
        button:hover {
            background-color: #16a085;
        }
        .error {
            color: #e74c3c;
            padding: 10px;
            background-color: rgba(231, 76, 60, 0.1);
            border-left: 4px solid #e74c3c;
            margin-bottom: 15px;
        }
        .success {
            color: #2ecc71;
            padding: 10px;
            background-color: rgba(46, 204, 113, 0.1);
            border-left: 4px solid #2ecc71;
            margin-bottom: 15px;
        }
    </style>
</head>
<body>
    <div class="install-container">
        <h1>Blackjack PHP Installation</h1>
        
        <?php if ($error): ?>
            <div class="error"><?php echo $error; ?></div>
        <?php endif; ?>
        
        <?php if ($success): ?>
            <div class="success">
                <?php echo $success; ?>
                <p>Click the button below to go to the homepage:</p>
                <button onclick="window.location.href='../index.php'">Go to Homepage</button>
            </div>
        <?php else: ?>
            <p>Welcome to the Blackjack PHP installation wizard. Please provide your database details below:</p>
            
            <form method="post" action="">
                <div class="form-group">
                    <label for="db_host">Database Host:</label>
                    <input type="text" id="db_host" name="db_host" value="<?php echo isset($_POST['db_host']) ? htmlspecialchars($_POST['db_host']) : 'localhost'; ?>" required>
                </div>
                
                <div class="form-group">
                    <label for="db_name">Database Name:</label>
                    <input type="text" id="db_name" name="db_name" value="<?php echo isset($_POST['db_name']) ? htmlspecialchars($_POST['db_name']) : 'blackjack'; ?>" required>
                </div>
                
                <div class="form-group">
                    <label for="db_user">Database Username:</label>
                    <input type="text" id="db_user" name="db_user" value="<?php echo isset($_POST['db_user']) ? htmlspecialchars($_POST['db_user']) : ''; ?>" required>
                </div>
                
                <div class="form-group">
                    <label for="db_pass">Database Password:</label>
                    <input type="password" id="db_pass" name="db_pass" value="<?php echo isset($_POST['db_pass']) ? htmlspecialchars($_POST['db_pass']) : ''; ?>">
                </div>
                
                <button type="submit">Install</button>
            </form>
        <?php endif; ?>
    </div>
</body>
</html>